### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by RealDaMotherYeeter** [NathanKassab/SpicyClient#17]
Any ETA on the Modifying the code and Exporting sections of ReadMe? There are some PR's that I could make but I cant get the workspace up properly. I think you should just post your modcoderpack folders (the important ones) so someone could extract them into MCP to modify the code.

**Comment by NathanKassab** [comment]
I don't post the mcp folder themselves because they can contain private things like alt account logins, also I don't know what you mean but eta

**Comment by YeahOMA** [comment]
I think he means when are you going to fill out the "Modifying" and "Exporting" sections of the README so people can get the project setup correctly in Eclipse.

**Comment by RealDaMotherYeeter** [comment]
Yes, I mean the Modifying and Exporting things. I don't see why you cant keep the alts in the `.gitignore` file. You could also use [this tutorial](https://www.youtube.com/watch?v=_JOI-iBH1z0) to convert MCP into a gradle project to make building easier (ofc you change a couple of things for 1.8.9) and then recommitting the gradle project.

**Comment by NathanKassab** [comment]
I don't know, it seems like it would be a real pain to change the repo to include the entire folder. I might convert it to a maven project though since maven is useful. As for filling out the modifying and exporting sections, I will most likely make a video on it showing how to do it since a lot has changed since the last time I made a tutorial on it. So hopefully soon
